/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cal_Cal */

#ifndef _Included_cal_Cal
#define _Included_cal_Cal
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
